apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deployment
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: darouich/config-service:latest
          ports:
            - containerPort: 9999
---

kind: Service
apiVersion: v1
metadata:
  name: config-service-svc
spec:
  selector:
    app: config-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9999
