apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
  labels:
    app: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: darouich/customer-service:latest
          ports:
            - containerPort: 8081
---

kind: Service
apiVersion: v1
metadata:
  name: customer-service-svc
spec:
  selector:
    app: customer-service
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
