apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  discovery_service_url: "http://eureka-0.eureka:8761/eureka"
---

kind: Service
apiVersion: v1
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: eureka
  selector:
    app: eureka

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: "eureka"
  template:
    metadata:
      labels:
        app: eureka

    spec:
      containers:
        - name: eureka
          image: darouich/discovery-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: DISCOVERY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: discovery_service_url
                  name: eureka-cm

---

kind: Service
apiVersion: v1
metadata:
  name: eureka-lb
  labels:
    app: eureka
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761
  selector:
    app: eureka

