apiVersion: apps/v1
kind: Deployment
metadata:
  name: vente-service-deployment
  labels:
    app: vente-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vente-service
  template:
    metadata:
      labels:
        app: vente-service
    spec:
      containers:
        - name: vente-service
          image: darouich/vente-service:latest
          ports:
            - containerPort: 8084
---

kind: Service
apiVersion: v1
metadata:
  name: vente-service-svc
spec:
  selector:
    app: vente-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8084
